version: "3.8"

services:
  app:
    image: ${BACKEND_IMAGE:-tekstura-backend:latest}
    container_name: laravel_app_prod
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_DATABASE: tekstura
      DB_USERNAME: laravel
      DB_PASSWORD: ${DB_PASSWORD}
      APP_ENV: production
      APP_DEBUG: "false"
    volumes:
      - app_storage:/var/www/html/storage
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h postgres_db -p 5432 -U laravel"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:15
    container_name: postgres_db_prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: articles_db
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backups:/backups
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: ${FRONTEND_IMAGE:-tekstura-frontend:latest}
    container_name: nuxt_frontend_prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 3000
      API_BASE_URL: http://laravel_app:9000/api
    depends_on:
      - app
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: reverse_proxy_prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - app
    networks:
      - app-network

volumes:
  db_data:
  app_storage:

networks:
  app-network:
    driver: bridge
