name: Deploy Frontend

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm run test --if-present
      
    - name: Build application
      run: npm run build
      env:
        API_BASE_URL: ${{ secrets.API_BASE_URL }}
        
    - name: Build Docker image
      run: |
        docker build -t tekstura-frontend:${{ github.sha }} .
        docker tag tekstura-frontend:${{ github.sha }} tekstura-frontend:latest
        
    - name: Deploy to staging
      if: github.ref == 'refs/heads/main'
      run: |
        # Здесь логика деплоя на staging
        echo "Deploying to staging..."
        # docker push registry.example.com/tekstura-frontend:staging
        
    - name: Deploy to production
      if: github.event_name == 'release'
      run: |
        # Здесь логика деплоя на production
        echo "Deploying to production..."
        # docker push registry.example.com/tekstura-frontend:latest
